//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Blog", Namespace="http://schemas.datacontract.org/2004/07/BlogLibrary")]
    [System.SerializableAttribute()]
    public partial class Blog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBlogService")]
    public interface IBlogService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/ShowBlogs", ReplyAction="http://tempuri.org/IBlogService/ShowBlogsResponse")]
        BlogClient.ServiceReference1.Blog[] ShowBlogs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/ShowBlogs", ReplyAction="http://tempuri.org/IBlogService/ShowBlogsResponse")]
        System.Threading.Tasks.Task<BlogClient.ServiceReference1.Blog[]> ShowBlogsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/ShowBlog", ReplyAction="http://tempuri.org/IBlogService/ShowBlogResponse")]
        BlogClient.ServiceReference1.Blog ShowBlog(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/ShowBlog", ReplyAction="http://tempuri.org/IBlogService/ShowBlogResponse")]
        System.Threading.Tasks.Task<BlogClient.ServiceReference1.Blog> ShowBlogAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/AddBlog", ReplyAction="http://tempuri.org/IBlogService/AddBlogResponse")]
        void AddBlog(string author_name, string title, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/AddBlog", ReplyAction="http://tempuri.org/IBlogService/AddBlogResponse")]
        System.Threading.Tasks.Task AddBlogAsync(string author_name, string title, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/UpdateBlog", ReplyAction="http://tempuri.org/IBlogService/UpdateBlogResponse")]
        bool UpdateBlog(int id, string author_name, string title, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/UpdateBlog", ReplyAction="http://tempuri.org/IBlogService/UpdateBlogResponse")]
        System.Threading.Tasks.Task<bool> UpdateBlogAsync(int id, string author_name, string title, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/DeleteBlog", ReplyAction="http://tempuri.org/IBlogService/DeleteBlogResponse")]
        bool DeleteBlog(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/DeleteBlog", ReplyAction="http://tempuri.org/IBlogService/DeleteBlogResponse")]
        System.Threading.Tasks.Task<bool> DeleteBlogAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBlogServiceChannel : BlogClient.ServiceReference1.IBlogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BlogServiceClient : System.ServiceModel.ClientBase<BlogClient.ServiceReference1.IBlogService>, BlogClient.ServiceReference1.IBlogService {
        
        public BlogServiceClient() {
        }
        
        public BlogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BlogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BlogClient.ServiceReference1.Blog[] ShowBlogs() {
            return base.Channel.ShowBlogs();
        }
        
        public System.Threading.Tasks.Task<BlogClient.ServiceReference1.Blog[]> ShowBlogsAsync() {
            return base.Channel.ShowBlogsAsync();
        }
        
        public BlogClient.ServiceReference1.Blog ShowBlog(int id) {
            return base.Channel.ShowBlog(id);
        }
        
        public System.Threading.Tasks.Task<BlogClient.ServiceReference1.Blog> ShowBlogAsync(int id) {
            return base.Channel.ShowBlogAsync(id);
        }
        
        public void AddBlog(string author_name, string title, string data) {
            base.Channel.AddBlog(author_name, title, data);
        }
        
        public System.Threading.Tasks.Task AddBlogAsync(string author_name, string title, string data) {
            return base.Channel.AddBlogAsync(author_name, title, data);
        }
        
        public bool UpdateBlog(int id, string author_name, string title, string data) {
            return base.Channel.UpdateBlog(id, author_name, title, data);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateBlogAsync(int id, string author_name, string title, string data) {
            return base.Channel.UpdateBlogAsync(id, author_name, title, data);
        }
        
        public bool DeleteBlog(int id) {
            return base.Channel.DeleteBlog(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteBlogAsync(int id) {
            return base.Channel.DeleteBlogAsync(id);
        }
    }
}
